"use strict";var _slicedToArray=(function(){function sliceIterator(arr,i){var _arr=[];var _n=true;var _d=false;var _e=undefined;try{for(var _i=arr[Symbol.iterator](),_s;!(_n=(_s=_i.next()).done);_n=true){_arr.push(_s.value);if(i&&_arr.length===i)break;}}catch(err){_d=true;_e=err;}finally{try{if(!_n&&_i["return"])_i["return"]();}finally{if(_d)throw _e;}}return _arr;}return function(arr,i){if(Array.isArray(arr)){return arr;}else if(Symbol.iterator in Object(arr)){return sliceIterator(arr,i);}else{throw new TypeError("Invalid attempt to destructure non-iterable instance");}};})();var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};})();function _typeof(obj){return obj&&typeof Symbol!=="undefined"&&obj.constructor===Symbol?"symbol":typeof obj;}
function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}
(function(){var Codebird=(function(){function Codebird(){_classCallCheck(this,Codebird);this._oauth_consumer_key=null;this._oauth_consumer_secret=null;this._oauth_bearer_token=null;this._endpoint_base="https://api.twitter.com/";this._endpoint_base_media="https://upload.twitter.com/";this._endpoint=this._endpoint_base+"1.1/";this._endpoint_media=this._endpoint_base_media+"1.1/";this._endpoint_publish="https://publish.twitter.com/";this._endpoint_oauth=this._endpoint_base;this._endpoint_proxy="https://api.jublo.net/codebird/";this._use_proxy=typeof navigator!=="undefined"&&typeof navigator.userAgent!=="undefined";this._oauth_token=null;this._oauth_token_secret=null;this._version="3.0.0-dev";this.b64_alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";}
_createClass(Codebird,[{key:"setConsumerKey",value:function setConsumerKey(key,secret){this._oauth_consumer_key=key;this._oauth_consumer_secret=secret;}},{key:"setBearerToken",value:function setBearerToken(token){this._oauth_bearer_token=token;}},{key:"getVersion",value:function getVersion(){return this._version;}},{key:"setToken",value:function setToken(token,secret){this._oauth_token=token;this._oauth_token_secret=secret;}},{key:"logout",value:function logout(){this._oauth_token=this._oauth_token_secret=null;return true;}},{key:"setUseProxy",value:function setUseProxy(use_proxy){this._use_proxy=!!use_proxy;}},{key:"setProxy",value:function setProxy(proxy){if(!proxy.match(/\/$/)){proxy+="/";}
this._endpoint_proxy=proxy;}},{key:"_url",value:function _url(data){if(/boolean|number|string/.test(typeof data==="undefined"?"undefined":_typeof(data))){return encodeURIComponent(data).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A");}else{return "";}}},{key:"_sha1",value:function _sha1(e){function n(e,b){e[b>>5]|=128<<24-b%32;e[(b+64>>9<<4)+15]=b;for(var c=new Array(80),a=1732584193,d=-271733879,h=-1732584194,k=271733878,g=-1009589776,p=0;p<e.length;p+=16){for(var o=a,q=d,r=h,s=k,t=g,f=0;80>f;f++){var m=undefined;if(f<16){m=e[p+f];}else{m=c[f-3]^c[f-8]^c[f-14]^c[f-16];m=m<<1|m>>>31;}
c[f]=m;m=l(l(a<<5|a>>>27,20>f?d&h|~d&k:40>f?d^h^k:60>f?d&h|d&k|h&k:d^h^k),l(l(g,c[f]),20>f?1518500249:40>f?1859775393:60>f?-1894007588:-899497514));g=k;k=h;h=d<<30|d>>>2;d=a;a=m;}
a=l(a,o);d=l(d,q);h=l(h,r);k=l(k,s);g=l(g,t);}
return[a,d,h,k,g];}
function l(e,b){var c=(e&65535)+(b&65535);return(e>>16)+(b>>16)+(c>>16)<<16|c&65535;}
function q(e){for(var b=[],c=(1<<g)-1,a=0;a<e.length*g;a+=g){b[a>>5]|=(e.charCodeAt(a/g)&c)<<24-a%32;}
return b;}
var g=8;var b=this._oauth_consumer_secret+"&"+(null!==this._oauth_token_secret?this._oauth_token_secret:"");if(this._oauth_consumer_secret===null){throw "To generate a hash, the consumer secret must be set.";}
var c=q(b);if(c.length>16){c=n(c,b.length*g);}
var bb=new Array(16);for(var a=new Array(16),d=0;d<16;d++){a[d]=c[d]^909522486;bb[d]=c[d]^1549556828;}
c=n(a.concat(q(e)),512+e.length*g);bb=n(bb.concat(c),672);b="";for(g=0;g<4*bb.length;g+=3){for(d=(bb[g>>2]>>8*(3-g%4)&255)<<16|(bb[g+1>>2]>>8*(3-(g+1)%4)&255)<<8|bb[g+2>>2]>>8*(3-(g+2)%4)&255,e=0;4>e;e++){b=8*g+6*e>32*bb.length?b+"=":b+this.b64_alphabet.charAt(d>>6*(3-e)&63);}}
return b;}},{key:"_base64_encode",value:function _base64_encode(a){var d=undefined,e=undefined,f=undefined,b=undefined,g=0,h=0,i=this.b64_alphabet,c=[];if(!a){return a;}
do{d=a.charCodeAt(g++);e=a.charCodeAt(g++);f=a.charCodeAt(g++);b=d<<16|e<<8|f;d=b>>18&63;e=b>>12&63;f=b>>6&63;b&=63;c[h++]=i.charAt(d)+i.charAt(e)+i.charAt(f)+i.charAt(b);}while(g<a.length);i=c.join("");a=a.length%3;return(a?i.slice(0,a-3):i)+"===".slice(a||3);}},{key:"_http_build_query",value:function _http_build_query(e,f,b){function g(c,a,d){var b=undefined,e=[];if(a===true){a="1";}else if(a===false){a="0";}
if(null!==a){if((typeof a==="undefined"?"undefined":_typeof(a))==="object"){for(b in a){if(a.hasOwnProperty(b)&&a[b]!==null){e.push(g.call(this,c+"["+b+"]",a[b],d));}}
return e.join(d);}
if(typeof a!=="function"){return this._url(c)+"="+this._url(a);}
throw "There was an error processing for http_build_query().";}else{return "";}}
var d,c,h=[];if(!b){b="&";}
for(c in e){if(!e.hasOwnProperty(c)){continue;}
d=e[c];if(f&&!isNaN(c)){c=String(f)+c;}
d=g.call(this,c,d,b);if(d!==""){h.push(d);}}
return h.join(b);}},{key:"_nonce",value:function _nonce(){var length=arguments.length<=0||arguments[0]===undefined?8:arguments[0];if(length<1){throw "Invalid nonce length.";}
var nonce="";for(var i=0;i<length;i++){var character=Math.floor(Math.random()*61);nonce+=this.b64_alphabet.substring(character,character+1);}
return nonce;}},{key:"_ksort",value:function _ksort(input_arr){var keys=[],sorter=undefined,k=undefined;sorter=function(a,b){var a_float=parseFloat(a),b_float=parseFloat(b),a_numeric=a_float+""===a,b_numeric=b_float+""===b;if(a_numeric&&b_numeric){return a_float>b_float?1:a_float<b_float?-1:0;}else if(a_numeric&&!b_numeric){return 1;}else if(!a_numeric&&b_numeric){return-1;}
return a>b?1:a<b?-1:0;};for(k in input_arr){if(input_arr.hasOwnProperty(k)){keys.push(k);}}
keys.sort(sorter);return keys;}},{key:"_clone",value:function _clone(obj){var clone={};for(var i in obj){if(_typeof(obj[i])==="object"){clone[i]=this._clone(obj[i]);}else{clone[i]=obj[i];}}
return clone;}},{key:"_getXmlRequestObject",value:function _getXmlRequestObject(){var xml=null;if((typeof window==="undefined"?"undefined":_typeof(window))==="object"&&window&&typeof window.XMLHttpRequest!=="undefined"){xml=new window.XMLHttpRequest();}else if((typeof Ti==="undefined"?"undefined":_typeof(Ti))==="object"&&Ti&&typeof Ti.Network.createHTTPClient!=="undefined"){xml=Ti.Network.createHTTPClient();}else if(typeof ActiveXObject!=="undefined"){try{xml=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){throw "ActiveXObject object not defined.";}}else if(typeof require==="function"){var XMLHttpRequest;try{XMLHttpRequest=require("xmlhttprequest").XMLHttpRequest;xml=new XMLHttpRequest();}catch(e1){try{XMLHttpRequest=require("xhr2");xml=new XMLHttpRequest();}catch(e2){throw "xhr2 object not defined, cancelling.";}}}
return xml;}},{key:"_parse_str",value:function _parse_str(str,array){var glue1="=",glue2="&",array2=String(str).replace(/^&?([\s\S]*?)&?$/,"$1").split(glue2),i,j,chr,tmp,key,value,bracket,keys,evalStr,fixStr=function fixStr(str){return decodeURIComponent(str).replace(/([\\"'])/g,"\\$1").replace(/\n/g,"\\n").replace(/\r/g,"\\r");};if(!array){array=this.window;}
for(i=0;i<array2.length;i++){tmp=array2[i].split(glue1);if(tmp.length<2){tmp=[tmp,""];}
key=fixStr(tmp[0]);value=fixStr(tmp[1]);while(key.charAt(0)===" "){key=key.substr(1);}
if(key.indexOf("\0")>-1){key=key.substr(0,key.indexOf("\0"));}
if(key&&key.charAt(0)!=="["){keys=[];bracket=0;for(j=0;j<key.length;j++){if(key.charAt(j)==="["&&!bracket){bracket=j+1;}else if(key.charAt(j)==="]"){if(bracket){if(!keys.length){keys.push(key.substr(0,bracket-1));}
keys.push(key.substr(bracket,j-bracket));bracket=0;if(key.charAt(j+1)!=="["){break;}}}}
if(!keys.length){keys=[key];}
for(j=0;j<keys[0].length;j++){chr=keys[0].charAt(j);if(chr===" "||chr==="."||chr==="["){keys[0]=keys[0].substr(0,j)+"_"+keys[0].substr(j+1);}
if(chr==="["){break;}}
evalStr="array";for(j=0;j<keys.length;j++){key=keys[j];if(key!==""&&key!==" "||j===0){key="'"+key+"'";}else{key=eval(evalStr+".push([]);")-1;}
evalStr+="["+key+"]";if(j!==keys.length-1&&eval("typeof "+evalStr)==="undefined"){eval(evalStr+" = [];");}}
evalStr+=" = '"+value+"';\n";eval(evalStr);}}}},{key:"getApiMethods",value:function getApiMethods(){var httpmethods={GET:["account/settings","account/verify_credentials","application/rate_limit_status","blocks/ids","blocks/list","collections/entries","collections/list","collections/show","direct_messages","direct_messages/sent","direct_messages/show","favorites/list","followers/ids","followers/list","friends/ids","friends/list","friendships/incoming","friendships/lookup","friendships/lookup","friendships/no_retweets/ids","friendships/outgoing","friendships/show","geo/id/:place_id","geo/reverse_geocode","geo/search","geo/similar_places","help/configuration","help/languages","help/privacy","help/tos","lists/list","lists/members","lists/members/show","lists/memberships","lists/ownerships","lists/show","lists/statuses","lists/subscribers","lists/subscribers/show","lists/subscriptions","mutes/users/ids","mutes/users/list","oauth/authenticate","oauth/authorize","saved_searches/list","saved_searches/show/:id","search/tweets","site","statuses/firehose","statuses/home_timeline","statuses/mentions_timeline","statuses/oembed","statuses/retweeters/ids","statuses/retweets/:id","statuses/retweets_of_me","statuses/sample","statuses/show/:id","statuses/user_timeline","trends/available","trends/closest","trends/place","user","users/contributees","users/contributors","users/profile_banner","users/search","users/show","users/suggestions","users/suggestions/:slug","users/suggestions/:slug/members"],POST:["account/remove_profile_banner","account/settings__post","account/update_delivery_device","account/update_profile","account/update_profile_background_image","account/update_profile_banner","account/update_profile_colors","account/update_profile_image","blocks/create","blocks/destroy","collections/create","collections/destroy","collections/entries/add","collections/entries/curate","collections/entries/move","collections/entries/remove","collections/update","direct_messages/destroy","direct_messages/new","favorites/create","favorites/destroy","friendships/create","friendships/destroy","friendships/update","lists/create","lists/destroy","lists/members/create","lists/members/create_all","lists/members/destroy","lists/members/destroy_all","lists/subscribers/create","lists/subscribers/destroy","lists/update","media/upload","mutes/users/create","mutes/users/destroy","oauth/access_token","oauth/request_token","oauth2/invalidate_token","oauth2/token","saved_searches/create","saved_searches/destroy/:id","statuses/destroy/:id","statuses/filter","statuses/lookup","statuses/retweet/:id","statuses/unretweet/:id","statuses/update","statuses/update_with_media","users/lookup","users/report_spam"]};return httpmethods;}},{key:"_getDfd",value:function _getDfd(){if(typeof window!=="undefined"){if(typeof window.jQuery!=="undefined"&&window.jQuery.Deferred){return window.jQuery.Deferred();}
if(typeof window.Q!=="undefined"&&window.Q.defer){return window.Q.defer();}
if(typeof window.RSVP!=="undefined"&&window.RSVP.defer){return window.RSVP.defer();}
if(typeof window.when!=="undefined"&&window.when.defer){return window.when.defer();}}
if(typeof require!=="undefined"){var promise_class=false;try{promise_class=require("jquery");}catch(e){}
if(promise_class){return promise_class.Deferred();}
try{promise_class=require("q");}catch(e){}
if(!promise_class){try{promise_class=require("rsvp");}catch(e){}}
if(!promise_class){try{promise_class=require("when");}catch(e){}}
if(promise_class){try{return promise_class.defer();}catch(e){}}}
return false;}},{key:"_getPromise",value:function _getPromise(dfd){if(typeof dfd.promise==="function"){return dfd.promise();}
return dfd.promise;}},{key:"_parseApiParams",value:function _parseApiParams(params){var apiparams={};if((typeof params==="undefined"?"undefined":_typeof(params))==="object"){apiparams=params;}else{this._parse_str(params,apiparams);}
return apiparams;}},{key:"_stringifyNullBoolParams",value:function _stringifyNullBoolParams(apiparams){for(var key in apiparams){if(!apiparams.hasOwnProperty(key)){continue;}
var value=apiparams[key];if(value===null){apiparams[key]="null";}else if(value===true||value===false){apiparams[key]=value?"true":"false";}}
return apiparams;}},{key:"_mapFnInsertSlashes",value:function _mapFnInsertSlashes(fn){return fn.split("_").join("/");}},{key:"_mapFnRestoreParamUnderscores",value:function _mapFnRestoreParamUnderscores(method){var url_parameters_with_underscore=["screen_name","place_id"];var i=undefined,param=undefined,replacement_was=undefined;for(i=0;i<url_parameters_with_underscore.length;i++){param=url_parameters_with_underscore[i].toUpperCase();replacement_was=param.split("_").join("/");method=method.split(replacement_was).join(param);}
return method;}},{key:"_mapFnToApiMethod",value:function _mapFnToApiMethod(fn,apiparams){var method="",param=undefined,i=undefined,j=undefined;method=this._mapFnInsertSlashes(fn);method=this._mapFnRestoreParamUnderscores(method);var method_template=method;var match=method.match(/[A-Z_]{2,}/);if(match){for(i=0;i<match.length;i++){param=match[i];var param_l=param.toLowerCase();method_template=method_template.split(param).join(":"+param_l);if(typeof apiparams[param_l]==="undefined"){for(j=0;j<26;j++){method_template=method_template.split(String.fromCharCode(65+j)).join("_"+String.fromCharCode(97+j));}
throw "To call the templated method \""+method_template+"\", specify the parameter value for \""+param_l+"\".";}
method=method.split(param).join(apiparams[param_l]);delete apiparams[param_l];}}
for(i=0;i<26;i++){method=method.split(String.fromCharCode(65+i)).join("_"+String.fromCharCode(97+i));method_template=method_template.split(String.fromCharCode(65+i)).join("_"+String.fromCharCode(97+i));}
return[method,method_template];}},{key:"_detectMethod",value:function _detectMethod(method,params){if(typeof params.httpmethod!=="undefined"){var httpmethod=params.httpmethod;delete params.httpmethod;return httpmethod;}
switch(method){case "account/settings":case "account/login_verification_enrollment":case "account/login_verification_request":method=Object.keys(params).length?method+"__post":method;break;}
var apimethods=this.getApiMethods();for(var httpmethod in apimethods){if(apimethods.hasOwnProperty(httpmethod)&&apimethods[httpmethod].indexOf(method)>-1){return httpmethod;}}
throw "Can't find HTTP method to use for \""+method+"\".";}},{key:"_detectMultipart",value:function _detectMultipart(method){var multiparts=["statuses/update_with_media","media/upload","account/update_profile_background_image","account/update_profile_image","account/update_profile_banner"];return multiparts.indexOf(method)>-1;}},{key:"_getSignature",value:function _getSignature(httpmethod,method,keys,base_params){var base_string="",key=undefined,value=undefined;for(var i=0;i<keys.length;i++){key=keys[i];value=base_params[key];base_string+=key+"="+this._url(value)+"&";}
base_string=base_string.substring(0,base_string.length-1);return this._sha1(httpmethod+"&"+this._url(method)+"&"+this._url(base_string));}},{key:"_time",value:function _time(){return Math.round(new Date().getTime()/1000);}},{key:"_sign",value:function _sign(httpmethod,method){var params=arguments.length<=2||arguments[2]===undefined?{}:arguments[2];if(this._oauth_consumer_key===null){throw "To generate a signature, the consumer key must be set.";}
var sign_params={consumer_key:this._oauth_consumer_key,version:"1.0",timestamp:this._time(),nonce:this._nonce(),signature_method:"HMAC-SHA1"};var sign_base_params={};for(var key in sign_params){if(!sign_params.hasOwnProperty(key)){continue;}
var value=sign_params[key];sign_base_params["oauth_"+key]=this._url(value);}
if(this._oauth_token!==null){sign_base_params.oauth_token=this._url(this._oauth_token);}
var oauth_params=this._clone(sign_base_params);for(key in params){if(!params.hasOwnProperty(key)){continue;}
sign_base_params[key]=params[key];}
var keys=this._ksort(sign_base_params);var signature=this._getSignature(httpmethod,method,keys,sign_base_params);params=oauth_params;params.oauth_signature=signature;keys=this._ksort(params);var authorization="OAuth ";for(var i=0;i<keys.length;i++){key=keys[i];authorization+=key+"=\""+this._url(params[key])+"\", ";}
return authorization.substring(0,authorization.length-2);}},{key:"_buildMultipart",value:function _buildMultipart(method,params){if(!this._detectMultipart(method)){return;}
var possible_methods=["media/upload","statuses/update_with_media","account/update_profile_background_image","account/update_profile_image","account/update_profile_banner"];var possible_files={"media/upload":"media","statuses/update_with_media":"media[]","account/update_profile_background_image":"image","account/update_profile_image":"image","account/update_profile_banner":"banner"};if(possible_methods.indexOf(method)===-1){return;}
possible_files=possible_files[method].split(" ");var multipart_border="--------------------"+this._nonce();var multipart_request="";for(var key in params){if(!params.hasOwnProperty(key)){continue;}
multipart_request+="--"+multipart_border+"\r\nContent-Disposition: form-data; name=\""+key+"\"";if(possible_files.indexOf(key)===-1){multipart_request+="\r\nContent-Transfer-Encoding: base64";}
multipart_request+="\r\n\r\n"+params[key]+"\r\n";}
multipart_request+="--"+multipart_border+"--";return multipart_request;}},{key:"_detectMedia",value:function _detectMedia(method){var medias=["media/upload"];return medias.indexOf(method)>-1;}},{key:"_detectJsonBody",value:function _detectJsonBody(method){var json_bodies=["collections/entries/curate"];return json_bodies.indexOf(method)>-1;}},{key:"_getEndpoint",value:function _getEndpoint(method){var url=undefined;if(method.substring(0,5)==="oauth"){url=this._endpoint_oauth+method;}else if(this._detectMedia(method)){url=this._endpoint_media+method+".json";}else if(method==="statuses/oembed"){url=this._endpoint_publish+"oembed";}else{url=this._endpoint+method+".json";}
return url;}},{key:"_parseApiReply",value:function _parseApiReply(reply){if(typeof reply!=="string"||reply===""){return{};}
if(reply==="[]"){return[];}
var parsed=undefined;try{parsed=JSON.parse(reply);}catch(e){parsed={};var elements=reply.split("&");for(var i=0;i<elements.length;i++){var element=elements[i].split("=",2);if(element.length>1){parsed[element[0]]=decodeURIComponent(element[1]);}else{parsed[element[0]]=null;}}}
return parsed;}},{key:"oauth_authenticate",value:function oauth_authenticate(){var params=arguments.length<=0||arguments[0]===undefined?{}:arguments[0];var callback=arguments.length<=1||arguments[1]===undefined?undefined:arguments[1];var type=arguments.length<=2||arguments[2]===undefined?"authenticate":arguments[2];var dfd=this._getDfd();if(typeof params.force_login==="undefined"){params.force_login=null;}
if(typeof params.screen_name==="undefined"){params.screen_name=null;}
if(["authenticate","authorize"].indexOf(type)===-1){type="authenticate";}
if(this._oauth_token===null){var error="To get the "+type+" URL, the OAuth token must be set.";if(dfd){dfd.reject({error:error});return this._getPromise(dfd);}
throw error;}
var url=this._endpoint_oauth+"oauth/"+type+"?oauth_token="+this._url(this._oauth_token);if(params.force_login===true){url+="&force_login=1";}
if(params.screen_name!==null){url+="&screen_name="+params.screen_name;}
if(typeof callback==="function"){callback(url);}
if(dfd){dfd.resolve({reply:url});return this._getPromise(dfd);}
return true;}},{key:"oauth_authorize",value:function oauth_authorize(params,callback){return this.oauth_authenticate(params,callback,"authorize");}},{key:"oauth2_token",value:function oauth2_token(callback){var _this=this;var dfd=this._getDfd();if(this._oauth_consumer_key===null){var error="To obtain a bearer token, the consumer key must be set.";if(dfd){dfd.reject({error:error});return this._getPromise(dfd);}
throw error;}
if(!dfd&&typeof callback==="undefined"){callback=function(){};}
var post_fields="grant_type=client_credentials";var url=this._endpoint_oauth+"oauth2/token";if(this._use_proxy){url=url.replace(this._endpoint_base,this._endpoint_proxy);}
var xml=this._getXmlRequestObject();if(xml===null){return;}
xml.open("POST",url,true);xml.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xml.setRequestHeader((this._use_proxy?"X-":"")+"Authorization","Basic "+this._base64_encode(this._oauth_consumer_key+":"+this._oauth_consumer_secret));xml.onreadystatechange=function(){if(xml.readyState>=4){var httpstatus=12027;try{httpstatus=xml.status;}catch(e){}
var response="";try{response=xml.responseText;}catch(e){}
var reply=_this._parseApiReply(response);reply.httpstatus=httpstatus;if(httpstatus===200){_this.setBearerToken(reply.access_token);}
if(typeof callback==="function"){callback(reply);}
if(dfd){dfd.resolve({reply:reply});}}};xml.onerror=function(e){if(typeof callback==="function"){callback(null,e);}
if(dfd){dfd.reject(e);}};xml.timeout=30000;xml.send(post_fields);if(dfd){return this._getPromise(dfd);}}},{key:"_callApi",value:function _callApi(httpmethod,method){var params=arguments.length<=2||arguments[2]===undefined?{}:arguments[2];var multipart=arguments.length<=3||arguments[3]===undefined?false:arguments[3];var _this2=this;var app_only_auth=arguments.length<=4||arguments[4]===undefined?false:arguments[4];var callback=arguments.length<=5||arguments[5]===undefined?function(){}:arguments[5];var dfd=this._getDfd();var url=this._getEndpoint(method),authorization=null;var xml=this._getXmlRequestObject();if(xml===null){return;}
var post_fields=undefined;if(httpmethod==="GET"){var url_with_params=url;if(JSON.stringify(params)!=="{}"){url_with_params+="?"+this._http_build_query(params);}
if(!app_only_auth){authorization=this._sign(httpmethod,url,params);}
if(this._use_proxy){url_with_params=url_with_params.replace(this._endpoint_base,this._endpoint_proxy).replace(this._endpoint_base_media,this._endpoint_proxy);}
xml.open(httpmethod,url_with_params,true);}else{if(multipart){if(!app_only_auth){authorization=this._sign(httpmethod,url,{});}
params=this._buildMultipart(method,params);}else if(this._detectJsonBody(method)){authorization=this._sign(httpmethod,url,{});params=JSON.stringify(params);}else{if(!app_only_auth){authorization=this._sign(httpmethod,url,params);}
params=this._http_build_query(params);}
post_fields=params;if(this._use_proxy||multipart){url=url.replace(this._endpoint_base,this._endpoint_proxy).replace(this._endpoint_base_media,this._endpoint_proxy);}
xml.open(httpmethod,url,true);if(multipart){xml.setRequestHeader("Content-Type","multipart/form-data; boundary="+post_fields.split("\r\n")[0].substring(2));}else if(this._detectJsonBody(method)){xml.setRequestHeader("Content-Type","application/json");}else{xml.setRequestHeader("Content-Type","application/x-www-form-urlencoded");}}
if(app_only_auth){if(this._oauth_consumer_key===null&&this._oauth_bearer_token===null){var error="To make an app-only auth API request, consumer key or bearer token must be set.";if(dfd){dfd.reject({error:error});return this._getPromise(dfd);}
throw error;}
if(this._oauth_bearer_token===null){if(dfd){return this.oauth2_token().then(function(){return _this2._callApi(httpmethod,method,params,multipart,app_only_auth,callback);});}
this.oauth2_token(function(){_this2._callApi(httpmethod,method,params,multipart,app_only_auth,callback);});return;}
authorization="Bearer "+this._oauth_bearer_token;}
if(authorization!==null){xml.setRequestHeader((this._use_proxy?"X-":"")+"Authorization",authorization);}
xml.onreadystatechange=function(){if(xml.readyState>=4){var httpstatus=12027;try{httpstatus=xml.status;}catch(e){}
var response="";try{response=xml.responseText;}catch(e){}
var reply=_this2._parseApiReply(response);reply.httpstatus=httpstatus;var rate=null;if(typeof xml.getResponseHeader!=="undefined"&&xml.getResponseHeader("x-rate-limit-limit")!==""){rate={limit:xml.getResponseHeader("x-rate-limit-limit"),remaining:xml.getResponseHeader("x-rate-limit-remaining"),reset:xml.getResponseHeader("x-rate-limit-reset")};}
if(typeof callback==="function"){callback(reply,rate);}
if(dfd){dfd.resolve({reply:reply,rate:rate});}}};xml.onerror=function(e){if(typeof callback==="function"){callback(null,null,e);}
if(dfd){dfd.reject(e);}};xml.timeout=30000;xml.send(httpmethod==="GET"?null:post_fields);if(dfd){return this._getPromise(dfd);}
return true;}},{key:"__call",value:function __call(fn){var params=arguments.length<=1||arguments[1]===undefined?{}:arguments[1];var callback=arguments[2];var app_only_auth=arguments.length<=3||arguments[3]===undefined?false:arguments[3];if(typeof callback!=="function"&&typeof params==="function"){callback=params;params={};if(typeof callback==="boolean"){app_only_auth=callback;}}else if(typeof callback==="undefined"){callback=function(){};}
switch(fn){case "oauth_authenticate":case "oauth_authorize":return this[fn](params,callback);case "oauth2_token":return this[fn](callback);}
var apiparams=this._parseApiParams(params);apiparams=this._stringifyNullBoolParams(apiparams);if(fn==="oauth_requestToken"){this.setToken(null,null);}
var _mapFnToApiMethod2=this._mapFnToApiMethod(fn,apiparams);var _mapFnToApiMethod3=_slicedToArray(_mapFnToApiMethod2,2);var method=_mapFnToApiMethod3[0];var method_template=_mapFnToApiMethod3[1];var httpmethod=this._detectMethod(method_template,apiparams);var multipart=this._detectMultipart(method_template);return this._callApi(httpmethod,method,apiparams,multipart,app_only_auth,callback);}}]);return Codebird;})();;if((typeof module==="undefined"?"undefined":_typeof(module))==="object"&&module&&_typeof(module.exports)==="object"){module.exports=Codebird;}else{if((typeof window==="undefined"?"undefined":_typeof(window))==="object"&&window){window.Codebird=Codebird;}
if(typeof define==="function"&&define.amd){define("codebird",[],function(){return Codebird;});}}})();