jQuery(document).ready(function($){var params=aelia_eu_vat_assistant_params;var tax_based_on=params.tax_based_on;var vat_country='';var $self_certification_element=$('#customer_location_self_certified_field');var $eu_vat_element;var $eu_vat_field;var last_vat_number='';var get_vat_country=function(){if((tax_based_on=='shipping')&&$('#ship-to-different-address input').is(':checked')){var country_field_selector='#shipping_country';}
else{var country_field_selector='#billing_country';}
return $(country_field_selector).val();}
var sufficient_location_evidence=function(){var country_count={};country_count[$('#billing_country').val()]=++country_count[$('#billing_country').val()]||1;if(params.use_shipping_as_evidence&&(params.use_shipping_as_evidence!=0)){if($('#ship-to-different-address-checkbox').is(':checked')&&($('#shipping_country').length>0)){country_count[$('#shipping_country').val()]=++country_count[$('#shipping_country').val()]||1;}}
country_count[params.ip_address_country]=++country_count[params.ip_address_country]||1;for(var country_id in country_count){if((country_id!='')&&(country_count[country_id]>=2)){return true;}}
return false;}
var update_self_certification_element=function(){var show_element=true;if(($eu_vat_field)&&$eu_vat_field.prop('valid')&&(params.hide_self_cert_field_with_valid_vat==1)){show_element=false;}
else{switch(params.show_self_cert_field){case 'yes':show_element=true;break;case 'conflict-only':show_element=!sufficient_location_evidence();break;}}
var self_cert_label=params.user_interface.self_certification_field_title;$self_certification_element.find('.self_certification_label').html(self_cert_label.replace('{billing_country}',$('#billing_country option:selected').text()));if(show_element){$self_certification_element.fadeIn();}
else{$self_certification_element.fadeOut();}}
var hide_vat_number_field=function(){return!params.show_eu_vat_number_for_base_country&&(vat_country==params.shop_base_country);}
var validate_vat_number=function(){var vat_number=$eu_vat_field.val();if((vat_country+vat_number)==last_vat_number){return;}
if((vat_country=='')||(vat_number.trim()=='')){$eu_vat_field.prop('valid',false);if(is_vat_number_required(vat_country)){$eu_vat_element.addClass('woocommerce-invalid');}
update_self_certification_element();$(document).trigger('wc_aelia_euva_eu_vat_number_validation_number_incomplete',vat_country,vat_number);return;}
last_vat_number=vat_country+vat_number;var ajax_args={'action':'validate_eu_vat_number','country':vat_country,'vat_number':vat_number,'_ajax_nonce':params._ajax_nonce};$.get(params.ajax_url,ajax_args,function(response){var vat_number_valid=response?response.valid:false;$eu_vat_field.prop('valid',vat_number_valid);$eu_vat_element.toggleClass('woocommerce-invalid',!vat_number_valid);update_self_certification_element();$(document).trigger('wc_aelia_euva_eu_vat_number_validation_complete',response);}).fail(function(response){console.log("VAT validation request failed",response);});}
var is_vat_number_required=function(vat_country){var vat_country_is_in_eu=($.inArray(vat_country,params.eu_vat_countries)>=0);$billing_company_field=$('form #billing_company');var company_field_filled=($billing_company_field.length>0)&&($billing_company_field.val().trim()!='');if(hide_vat_number_field()){return false;}
var result=(params.eu_vat_field_required=='required')||((params.eu_vat_field_required=='required_for_eu_only')&&vat_country_is_in_eu)||((params.eu_vat_field_required=='required_if_company_field_filled')&&company_field_filled)||((params.eu_vat_field_required=='required_if_company_field_filled_eu_only')&&company_field_filled&&vat_country_is_in_eu);return result;}
var set_eu_vat_field_handlers=function(){var eu_vat_countries=params.eu_vat_countries;switch(tax_based_on){case 'billing':var event_selector='select#billing_country';break;case 'shipping':var event_selector='select#billing_country, select#shipping_country, input#ship-to-different-address-checkbox';break;default:var event_selector='select#billing_country';}
event_selector=event_selector+', #billing_company, #vat_number';$('form.checkout, #order_review').on('change',event_selector,function(){var previous_vat_country=vat_country;vat_country=get_vat_country();if($eu_vat_element.length>0){var vat_field_required=is_vat_number_required(vat_country);if(vat_country&&(($.inArray(vat_country,params.eu_vat_countries)>=0)&&!hide_vat_number_field())||vat_field_required){$eu_vat_element.fadeIn();}
else{$eu_vat_element.fadeOut(function(){$eu_vat_field.val('');});}
if($eu_vat_element.is(':visible')&&vat_field_required){$eu_vat_element.find('.form-row').addClass('validate-required');}
else{$eu_vat_element.find('.form-row').removeClass('validate-required');}
validate_vat_number();}
if($self_certification_element.length>0){update_self_certification_element();}});if($eu_vat_element.length>0){$eu_vat_field.on('blur',function(){validate_vat_number();});}}
if($('.woocommerce form.checkout').length>0){$eu_vat_element=$('#vat_number_field');if($eu_vat_element.length>0){$eu_vat_field=$eu_vat_element.find('#vat_number');}
if($self_certification_element.length>0){var $self_certification_description=$self_certification_element.find('.description');$self_certification_element.find('.woocommerce-input-wrapper').before($self_certification_description);}
set_eu_vat_field_handlers();$('select#billing_country').change();}});